config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get('/about' => 'about#index')
  get('/contact' => 'contact#index')
  post('/contact_submit' => 'contact#create')
  # get('/admin/panel' => 'dashboard#index')

  namespace :admin do
    resources :dashboard, only: :index
  end
  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :products
    end
  end

  # get('/admin/dashboard' => 'admin/dashboard#index')
  resources :products do
    resources :reviews, only: [:create, :destroy, :update]
    resources :favourites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create] do
    resources :likes, only: [:index]
    resources :favourites, only: [:index]
  end
  resources :sessions, only: [:new, :create]

  resources :reviews do
    resources :likes, only: [:create, :destroy]
  end

  # get('/products/new', { to: 'products#new', as: 'new_product'})
  #
  # post('/products', { to: 'products#create', as: 'products' })
  #
  # get('/products/:id', { to: 'products#show',  as: 'product' })
  #
  # get('/products', { to: 'products#index' })
  #
  # get('/products/:id/edit', { to: 'products#edit', as: 'edit_product'})
  #
  # patch('/products/:id', { to: 'products#update' })
  #
  # delete('/products/:id', { to: 'products#destroy' })

  resources :sessions, only:[:new, :create] do
     delete :destroy, on: :collection
     #password does not show in the address url
   end

  root 'welcome#index'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favouritors,  through: :favourites, source: :user
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  validates :title, presence: true, uniqueness: {case_sensitive: false}
  validates(:price, { presence: true,
                            numericality: { greater_than: 0 }})
  validates(:description,{ presence: true, length: { minimum: 10 } })

  before_save :set_defaults, :titleize_title

  def favourited_by?(user)
    favourites.exists?(user: user)
  end

  def favourite_for(user)
    favourites.find_by(user: user)
  end


  def self.search(string)
    self.where(["title ILIKE? or description ILIKE?", "%#{string}%","%#{string}%"])
  end

  def self.search(find)
     where('title ILIKE? OR body ILIKE ?',"%#{find}%", "%#{find}%").
     order('title')
   end

  def set_defaults
    self.price ||= 1
    end

  def titleize_title
    self.title =title.titleize if title.present?
    end

 end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
before_action :authenticate_user
skip_before_filter :verify_authenticity_token

def index
  @products = Product.all
end

def show
  @product = Product.find params[:id]
  # render json: @product
  # render :show
end

def create
  @product = Product.new title: params[:title], description: params[:description], price: params[:price]
  @product.user = @user
if @product.save
  render json: {result: 'product created'}
else
  render json: {result: @product.errors.full_messages.join(', ')}
end
  end

def destroy
  @product = Product.find params[:id]

  if @product.destroy
    render json: {result: 'product deleted'}
  else
    render json: {result: @product.errors.full_messages.join(', ')}, status: 500
  end
rescue ActiveRecord::RecordNotFound
  render json: {result: 'Product can not be found'}, status: 4041

end

def update
  @product = Product.find params[:id]
end




private
def authenticate_user
  @user = User.find_by_api_token params[:api_token]
  head :unauthorized if @user.nil?
end






end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @product = Product.new
  end

  def create
    product_params = params.require(:product).permit([:title, :description, :price, :category_id])
    @product = Product.new product_params
    @product.user = current_user
    if @product.save
      ProductsMailer.notify_product_owner(@product).deliver_now
      redirect_to products_path
    else
      render :new
  end
  end

  def index
    @products = Product.all
  end

  def show

    @product = Product.find params[:id]
    @review = Review.new

  end

  def destroy
    @product = Product.find params[:id]
    if can? :destroy, @product
     @product.destroy
     redirect_to products_path, notice: 'Product delete'
   else
     redirect_to root_path, alert: 'Access denied'
   end
  end

  def edit
    @product = Product.find params[:id]
    redirect_to root_path, alert: 'access denited' unless can? :edit, @product

  end



  def update
  @product = Product.find params[:id]
  product_params = params.require(:product).permit([:title, :description, :price, :category_id])

  if !(can? :edit, @product)
      redirect_to root_path, alert: 'acess denied'
    elsif @product.update(product_params.merge({ slug:nil}))
      redirect_to product_path(@product), notice: 'Product updated'
    else
      render :edit
    end
end

end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_for @product do |f| %>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>
<div>
    <%= f.label :description %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.text_field :price %>
</div>
<%= f.submit %>

<% end %>

app/views/products/index.html.erb
<h1>All Products</h1>

<% @products.each do |product| %>
<h3><%= link_to product.title, product_path(product) %></h3>
<% if user_signed_in? && can?(:favourite, product) %>
  <% if product.favourited_by?(current_user) %>
  <%= link_to fa_icon("heart"), product_favourite_path(product, product.favourite_for(current_user), origin: 'index'), method: :delete %>
  <% else %>
  <%= link_to fa_icon("heart-o"), product_favourites_path(product, origin: 'index'), method: :post %>
  <% end %>
<% end %>
<span><%= pluralize(product.favourites.count, 'favourite') %></span>
<p><%= product.user.first_name %></p>
<hr>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= @product.errors.full_messages.join(', ') %>
<%= form_for @product do |f| %>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>
<div>
    <%= f.label :description %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.text_field :price %>
</div>
<div>

<%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>

</div>

<%= f.submit %>

<% end %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p>$$<%= sprintf('%.2f', @product.price) %></p>
<p>Category ID: <%= @product.category_id %></p>
<p>Category Name: <%= @product.category.name %></p>
<p><%= @product.user.first_name %></p>




<% if user_signed_in? && can?(:favourite, @product)  %>
  <% if @product.favourited_by?(current_user) %>
  <%= link_to fa_icon("heart"), product_favourite_path(@product, @product.favourite_for(current_user)), method: :delete %>
  <% else %>
  <%= link_to fa_icon("heart-o"), product_favourites_path(@product), method: :post %>
  <% end %>
<% end %>
<span><%= pluralize(@product.favourites.count, 'favourite') %></span>



<br>
<% if can? :edit, @product %>
<%= link_to 'Edit', edit_product_path(@product) %>
<% end %>
<% if can? :destroy, @product %>
<%= link_to 'Delete', product_path(@product),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
<% end %>

<hr>

<h2>Reviews</h2>
<%= @review.errors.full_messages.join(', ') %>
<%= form_for [@product, @review] do |f| %>
  <%= f.text_area :body %>
  <%= f.select :rating, [1,2,3,4,5] %>
  <%= f.submit %>
<% end %>
<hr>
<% @product.reviews.each do |review| %>

<% if review.is_hidden == false %>
  <p>Review:<%= review.body %></p>
  <p><%= review.user.first_name %></p>
  <p>Rating:<%= review.rating %></p>

  <% if user_signed_in? && can?(:like, review) %>
  <% if review.liked_by?(current_user) %>
  <%= link_to "Remove Like", review_like_path(review, review.like_for(current_user)), class: 'btn btn-primary', method: :delete %>
  <% else %>
  <%= link_to "Like", review_likes_path(review),  class: 'btn btn-primary', method: :post %>
  <% end %>
  <% end %>
    <% if can? :update, review %>
      <%= link_to 'Hide', product_review_path(@product, review), class: 'btn btn-primary', method: :PATCH %>
      <%= link_to 'Delete', product_review_path(@product, review), class: 'btn btn-primary',
    method: :delete,
    data: { confirm: 'Are you sure?'} %>
  <% end %>

<% else %>
<p>Review:<%= review.body %></p>
<p><%= review.user.first_name %></p>
  <p>Rating:<%= review.rating %></p>
<%= link_to 'Show', product_review_path(@product, review), class: 'btn btn-primary', method: :PATCH %>
<%= link_to 'Delete', product_review_path(@product, review), class: 'btn btn-primary',
method: :delete,
data: { confirm: 'Are you sure?'} %>


<% end %>
<% end %>